FROM python:3.11-slim

WORKDIR /backend



RUN apt-get update && apt-get install -y \
    build-essential \
    libglib2.0-0 \
    libgirepository1.0-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


COPY . . 

ENV PYTHONPATH=/backend
ENV PATH="/root/.local/bin:$PATH"


CMD  ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "3000"]